version: '3.7'

services:
  bondai:
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - ../:/app
    env_file:
      - ../.env
    ports:
      - "3000:3000"
